### ISSUE TITLE
Puppeteer errors causing program termination

### ISSUE THREAD

**Issue by MCSeekeri** [openzim/zimit#376]
I was using Zimit to archive the SCP-CN Wikidot site and encountered an interruption of the program due to a puppeteer error.
Attached here is the log output before the program exits.
```
{"timestamp":"2024-08-27T08:36:03.741Z","logLevel":"warn","context":"behavior","message":"Waiting for custom page load failed","details":{"type":"exception","message":"Protocol error (Runtime.evaluate): Target closed","stack":"TargetCloseError: Protocol error (Runtime.evaluate): Target closed\n    at CallbackRegistry.clear (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)\n    at CdpCDPSession._onClosed (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:98:25)\n    at Connection.onMessage (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:127:25)\n    at WebSocket.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:38:32)\n    at callListener (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:290:14)\n    at WebSocket.onMessage (/app/node_modules/puppeteer-core/node_modules/ws/lib/event-target.js:209:9)\n    at WebSocket.emit (node:events:519:28)\n    at Receiver.receiverOnMessage (/app/node_modules/puppeteer-core/node_modules/ws/lib/websocket.js:1220:20)\n    at Receiver.emit (node:events:519:28)\n    at Immediate.<anonymous> (/app/node_modules/puppeteer-core/node_modules/ws/lib/receiver.js:601:16)"}}
{"timestamp":"2024-08-27T08:36:03.742Z","logLevel":"warn","context":"links","message":"Link Extraction failed","details":{"type":"exception","message":"Attempted to use detached Frame '9A153325AAEA4D188BAEBA1E8B6B9D41'.","stack":"Error: Attempted to use detached Frame '9A153325AAEA4D188BAEBA1E8B6B9D41'.\n    at CdpFrame.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:92:23)\n    at file:///app/dist/crawler.js:1378:102\n    at Array.map (<anonymous>)\n    at Crawler.extractLinks (file:///app/dist/crawler.js:1378:72)\n    at Crawler.loadPage (file:///app/dist/crawler.js:1322:20)\n    at async Crawler.default [as driver] (file:///app/dist/defaultDriver.js:2:5)\n    at async Crawler.crawlPage (file:///app/dist/crawler.js:566:9)\n    at async PageWorker.crawlPage (file:///app/dist/util/worker.js:153:21)"}}
[zimit::2024-08-27 08:36:04,142] INFO:SIGINT/SIGTERM received, stopping zimit
```
```
file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:72
            throw new Error('Execution context was destroyed');
                  ^

Error: Execution context was destroyed
    at file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:72:19
    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:1936:31
    at OperatorSubscriber2._this._next (file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:993:9)
    at Subscriber2.next (file:///app/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs.js:696:12)
    at listener (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/util.js:367:24)
    at file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:36:7
    at Array.map (<anonymous>)
    at Object.emit (file:///app/node_modules/puppeteer-core/lib/esm/third_party/mitt/mitt.js:35:20)
    at EventEmitter.emit (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/common/EventEmitter.js:77:23)
    at [nodejs.dispose] (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/IsolatedWorld.js:151:23)
```
docker-compose.yml:
```
services:
  openzim:
    image: ghcr.io/openzim/zimit:dev
    environment:
      - HTTP_PROXY=http://100.100.2.2:19999
      - HTTPS_PROXY=http://100.100.2.2:19999
    command:
      - zimit
      - --url=https://scp-wiki-cn.wikidot.com
      - --keep
      - --name=scp-wiki_zh_all
      - --title="SCP 基金会 wiki"
      - --output=/output
      - --exclude=(\?q=|/signin|/forum|/system:)
      - --verbose
      - --workers=64
      - --behaviors=autoplay,autofetch,siteSpecific,autoscroll
      - --lang=zh
      - --zim-lang=zh
      - --description="SCP 基金会中国分部数据存档"
    volumes:
      - ./output:/output
 ```
I've modified the configuration with reference to the existing [recipes](https://farm.openzim.org/recipes/scp-wiki_en), but I still encounter this problem.
