### ISSUE TITLE
`--config` doesn't keep old .tm folder

### ISSUE THREAD

**Issue by RichyHBM** [openzim/zimit#499]
As per the title, when you use `--config`, zimit still creates a new .tm folder for all data, which means at best it is going to have to re-download all data again, and at worse it will skip data it thinks it has already downloaded.

I propose a new cmd flag to specify the folder to use to download temporary files to

**Comment by benoit74** [comment]
Isn't the `--build` setting enough for that purpose?

**Comment by RichyHBM** [comment]
Do you have any docs on that flag? I can't find what it does

**Comment by benoit74** [comment]
`zimit --help` will help you on that

This `--build` flag allows you to specify in which directory you want to store temporary files downloaded by the scraper before building the ZIM.

**Comment by RichyHBM** [comment]
Great, that sounds like it is what I was suggesting, thank you!

**Comment by RichyHBM** [comment]
Actually, that doesn't fix the issue, as build tells it what folder to use as the parent of the temporary folder, but it still generates a randomly named folder for the scraped data

**Comment by RichyHBM** [comment]
Yes that seems to be the case, it may be simply the answer is that in this case I'd have to use the crawler directly

**Comment by benoit74** [comment]
For now, using the crawler directly and then invoking warc2zim on produced WARCs is definitely going to work. But I see no reason not to support this in zimit directly, only need to find how to develop it in a consistent manner, if we could avoid creating more CLI parameter it would probably help.

**Comment by RichyHBM** [comment]
Maybe if you are specifying the config with --config, it should force use the directory structure the config is in? From my understanding that structure is standard

**Comment by Routhinator** [comment]
This seems like an important gap to close in the design here, as I've been trying to workout how to manage zimit tasks as Kubernetes jobs, which inherently need to be interruptible when they run for a long time. Complex sites like wikis, and sites with ratelimiting, may need to be slowed to a point where they take several days to ensure success, and this means a need to be interrupted. 

However, since the config file for resumption cannot be known in advance when configuring the job, and the temp directory is constantly randomized without any consideration of the crawlID, the build directory param, etc - there seems to be no way to do this. Jobs can only be resumed manually - making any sort of sensible job automation impossible unless it succeeds in one try.

**Comment by Routhinator** [comment]
I have managed to confirm the above.

With this patch:

[resume_from_config_dir.patch](https://github.com/user-attachments/files/23319784/resume_from_config_dir.patch)

And this entrypoint:

`entrypoint.sh`
```bash

#!/usr/bin/env bash

############################
# Zimit Entrypoint for Jobs
############################

set -e

echo "##############################"
echo "Creating ZIM Archive of ${URL}"
echo "##############################"
echo ""

RESUME_CONFIG="$(find "${BUILD}"/.tmp* -regex ".*${CRAWLID}.yaml" -printf "%T+\t%p\n" 2>/dev/null | sort | awk '{print $2}' | tail -n 1)"

if [[ $RESUME_CONFIG ]]
then
    RESUME_CONFIG="--config ${RESUME_CONFIG}"
fi

zimit \
    --restartsOnError \
    --keep \
    ${RESUME_CONFIG} \
    --build "${BUILD}" \
    --crawlId "${CRAWLID}" \
    --healthCheckPort "${HEALTHCHECKPORT}" \
    --workers "${WORKERS}" \
    --saveState "${SAVESTATE}" \
    --pageExtraDelay "${PAGEEXTRADELAY}" \
    --pageLoadTimeout "${PAGELOADTIMEOUT}" \
    --postLoadDelay "${POSTLOADDELAY}" \
    --profile "${PROFILE}" \
    --blockAds "StevenBlack" \
    --seeds "${URL}" \
    --title "${TITLE}" \
    --description "${DESC}" \
    --long-description "${LONGDESC}" \
    --name "${NAME}"

echo ""
echo "##################################"
echo "Completed creation of ZIM Archive."
echo "##################################"
echo ""


```

Along with this example Pod definition:

`kustomization.yaml`
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: zimit-configmap
    files:
      - entrypoint.sh
```

`job-zim-example-site.yaml`
```yaml

---
apiVersion: batch/v1
kind: Job
metadata:
  name: zim-example-site
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      nodeName: gold01
      restartPolicy: Never
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
        fsGroup: 1000
      imagePullSecrets:
        - name: pull-secret-forgejo-home-routh-ca
      containers:
        - name: zimit
          image: forgejo.home.routh.ca/library/zimit:test3
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: BUILD
              value: /output
            - name: HEALTHCHECKPORT
              value: "8080"
            - name: WORKERS
              value: "4"
            - name: PAGEEXTRADELAY
              value: "60"
            - name: PAGELOADTIMEOUT
              value: "120"
            - name: POSTLOADDELAY
              value: "10"
            - name: PROFILE
              value: /crawls/profiles/exampleSiteProfile.tar.gz
            - name: CRAWLID
              value: example_site
            - name: SAVESTATE
              value: "always"
            - name: URL
              value: "https://examplesite.com"
            - name: TITLE
              value: "Example Site"
            - name: DESC
              value: "Demonstrating an interruptible Job Pod for Zimit"
            - name: LONGDESC
              value: |
                Some multiline desc
            - name: NAME
              value: "example_site_en_maxi"
          command:
            - /entrypoint.sh
          volumeMounts:
            - name: zimcache
              subPath: output
              mountPath: /output
            - name: zimcache
              subPath: crawls
              mountPath: /crawls
            - name: zimit-config
              subPath: entrypoint.sh
              mountPath: /entrypoint.sh
      volumes:
        - name: zimcache
          hostPath:
            path: /mnt/zimcache
        - name: zimit-config
          configMap:
            name: zimit-configmap
            defaultMode: 0777
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"

```
